######################################################################
# Automatically generated by qmake (2.01a) Sun May 8 14:37:56 2016
######################################################################

TEMPLATE = app
TARGET = RCA_Simulator 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += CImg.h customdialog.h
SOURCES += customdialog.cpp RCASimulator.cpp

# With C++11 support
greaterThan(QT_MAJOR_VERSION, 4){    
CONFIG += c++11
} else {
QMAKE_CXXFLAGS += -std=c++11
}



